name: Push to AWS
on:
  push:
    branches:
      - main

jobs:
  aws_push:
    steps:
      - name: Push to AWS
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: airflow-dev-dag-repo-update